#ifndef QTCVIMGCODECS_GLOBAL_H
#define QTCVIMGCODECS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCVIMGCODECS_LIBRARY)
#define QTCVIMGCODECS_EXPORT Q_DECL_EXPORT
#else
#define QTCVIMGCODECS_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCVIMGCODECS_GLOBAL_H
